// DPS Web Socket Event Constants
export const DPS_GAME_ID_EVENT = "DPS_GAME_ID_EVENT";
export const DPS_PLAYER_COUNT_EVENT = "DPS_PLAYER_COUNT_EVENT";
export const DPS_CONNECTED_EVENT = "DPS_CONNECTED_EVENT";
export const DPS_START_EVENT = "DPS_START_EVENT";
export const DPS_END_EVENT = "DPS_END_EVENT";
export const B_TIMES_EVENT='B_TIMES';
export const A_SUCCESS_EVENT='A_SUCCESS';
export const A_PHASES_EVENT = 'A_PHASES';
export const SWAP_ROLES_AND_RESTART_EVENT= 'SWAP_ROLES_AND_RESTART';
export const PLAYER_LEFT_EVENT = 'PLAYER_LEFT';


